### ISSUE TITLE
Possible bug. Behavior changes between "normal mode" and "debug mode"

### ISSUE THREAD

**Issue by Zardoz89** [Meisaka/isiCPU#1]
I try to debug my test2.dasm that uses BBOS calls to fill the screen with the whole charset on a infinite loop. On debug mode, fills the whole screen, however when I run it with debug mode, don't writes any thing on screen.

test2.dasm : https://github.com/Zardoz89/fun-with-dcpu-16/blob/develop/test2.dasm

```
  ./isicpu -s -r -e -B bbos.bin -d test.idi
```

Binary floppy image : 
[test.idi.zip](https://github.com/Meisaka/isiCPU/files/292291/test.idi.zip)

BBOS image taken from TC

**Comment by Meisaka** [comment]
should be fixed in 1439902

**Comment by Zardoz89** [comment]
Fixed
